on: workflow_dispatch
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - run: echo "FOO=bar" | tee -a $GITHUB_ENV

    - if: ${{ env.FOO == 'bar' }}
      run: echo "${{ env.FOO == 'bar' }}"

    - if: ${{ env.FOO }} == 'bar'
      run: echo "${{ env.FOO }} == 'bar'"

    - if: ${{ env.BAD == '' }}
      run: echo "${{ env.BAD == '' }}"

    - if: ${{ env.BAD }} == ''
      run: echo "${{ env.BAD }} == ''"

    - if: ${{ env.BAD  != '' }}
      run: echo "this should not print! ${{ env.BAD  != '' }}"

    - if: ${{ env.BAD }} != ''
      run: echo "this should not print ${{ env.BAD }} != ''"

    - run: |
         if ["$BAD" == ""]; then
            echo "sh check ["$BAD" == ""]"
         fi
