on: workflow_dispatch
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - run: echo "EXISTS=foo" | tee -a $GITHUB_ENV

    - run: echo "EXISTS=${{ env.EXISTS }}"
    - run: echo "UNSET=${{ env.UNSET }}"

    - if: ${{ env.EXISTS == 'bar' }}
      run: echo "{ env.EXISTS == 'bar' }"

    - if: ${{ env.EXISTS }} == 'bar'
      run: echo "{ env.EXISTS } == 'bar'"

    - if: ${{ env.UNSET == '' }}
      run: echo "{ env.UNSET == '' }"

    - if: ${{ env.UNSET }} == ''
      run: echo "{ env.UNSET } == ''"

    - if: ${{ env.UNSET  != '' }}
      run: echo "this should not print! { env.UNSET  != '' }"

    - if: ${{ env.UNSET }} != ''
      run: echo "this should not print! { env.UNSET } != ''"

    - run: |
         if ["$UNSET" == ""]; then
            echo "using ["$UNSET" == ""] within run"
         fi
