on: workflow_dispatch
jobs:
  use-libmamba-solver:
    runs-on: ubuntu-latest
    name: use-libmamba-solver (python=${{ matrix.python }})
    strategy:
      fail-fast: false
      matrix:
        python:
          - '3.6'
          - '3.7'
          - '3.8'
          - '3.9'
    defaults:
      run:
        shell: bash -l -eo pipefail {0}
    steps:
      - uses: conda-incubator/setup-miniconda@v2

      - run: conda install --override-channels -c conda-forge python=${{ matrix.python }}

      - run: |
          conda install -n base conda-libmamba-solver
          conda config --set solver libmamba

      - run: conda install -c bioconda -c conda-forge augur

  use-mambaforge:
    runs-on: ubuntu-latest
    name: use-mambaforge (python=${{ matrix.python }})
    strategy:
      fail-fast: false
      matrix:
        python:
          - '3.6'
          - '3.7'
          - '3.8'
          - '3.9'
    defaults:
      run:
        shell: bash -l -eo pipefail {0}
    steps:
      - uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: ${{ matrix.python }}
          miniforge-variant: Mambaforge
          activate-environment: test

      - run: mamba install -c bioconda augur
