# Debugging https://github.com/nextstrain/cli/pull/249.

on: workflow_dispatch
jobs:
  run:
    runs-on: ubuntu-latest
    name: python=${{ matrix.python }}
    strategy:
      fail-fast: false
      matrix:
        python:
          - '3.6'
          - '3.7'
          - '3.8'
          - '3.9'
    steps:
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: test

      - run: |
          conda install -n base conda-libmamba-solver
          conda config --set solver libmamba

      - run: conda install -c bioconda -c conda-forge augur auspice snakemake python=${{ matrix.python }}
        shell: bash -l -eo pipefail {0}

      - run: conda info
        shell: bash -l -eo pipefail {0}

      - run: conda list
        shell: bash -l -eo pipefail {0}

      # Assert that we're on the expected Python version, in case the GH
      # Actions environment is messed up.
      - run: type python
        shell: bash -l -eo pipefail {0}
      - run: python --version
        shell: bash -l -eo pipefail {0}
      - run: type python3
        shell: bash -l -eo pipefail {0}
      - run: python3 --version
        shell: bash -l -eo pipefail {0}
      - run: |
          python --version | grep -F 'Python ${{ matrix.python }}.'
          echo $?
        shell: bash -l -o pipefail {0}
        continue-on-error: true
      - run: |
          python3 --version | grep -F 'Python ${{ matrix.python }}.'
          echo $?
        shell: bash -l -o pipefail {0}
        continue-on-error: true
      - run: |
          echo "Python 3.6.13 :: Anaconda, Inc." | grep -F 'Python 3.6.'
          echo $?
        shell: bash -l -o pipefail {0}
        continue-on-error: true
      - run: |
          [[ "$(python --version)" == "$(python3 --version)" ]]
        shell: bash -l -eo pipefail {0}
