on:
  workflow_dispatch:
    inputs:
      run_parallel:
        required: true
        type: boolean
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - run: echo "${{ github.job }}"
  job2:
    runs-on: ubuntu-latest
    needs: ${{ github.event.inputs.run_parallel && [] || [job1] }}
    steps:
    - run: echo "${{ github.job }}"
