on:
  workflow_dispatch:
    inputs:
      run_parallel:
        required: true
        type: boolean
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - run: echo "${{ github.job }}"
  job2:
    runs-on: ubuntu-latest
    steps:
    - run: echo "${{ github.job }}"
  job3:
    runs-on: ubuntu-latest
    needs: ${{ github.event.inputs.run_parallel && [job1] || [job1, job2] }}
    steps:
    - run: echo "${{ github.job }}"
    - run: echo "${{ github.event.inputs.run_parallel }}"
