on: workflow_dispatch
jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - run: docker pull hello-world:latest
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: docker image push ghcr.io/hello-world:latest
  pull:
    needs: push
    runs-on: ubuntu-latest
    steps:
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: docker pull ghcr.io/hello-world:latest
