on: workflow_dispatch
jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - run: docker pull hello-world:latest
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: docker tag hello-world:latest ghcr.io/${{ github.actor }}/hello-world:latest
      - run: docker push ghcr.io/${{ github.actor }}/hello-world:latest
  pull:
    needs: push
    runs-on: ubuntu-latest
    steps:
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: docker pull ghcr.io/${{ github.actor }}/hello-world:latest
