on:
  workflow_dispatch:
    inputs:
      set_me_to_true:
        required: true
        type: boolean
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - if: true
      run: echo "hello"
    - if: true && true
      run: echo "hello"
    - if: true && false
      run: echo "hello"
    - if: ${{ !false || false }}
      run: echo "hello"
    - if: '!github.event.inputs.set_me_to_true'
      run: echo "this should not run"
    - if: "!github.event.inputs.set_me_to_true"
      run: echo "this should not run"
    - if: (!github.event.inputs.set_me_to_true)
      run: echo "this should not run"
    - if: ${{ !github.event.inputs.set_me_to_true }}
      run: echo "this should not run"
