on: push
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - run: echo "foo=${{ github.event_name == 'push' }}" >> $GITHUB_ENV
    - run: echo "bar=${{ github.event_name != 'push' }}" >> $GITHUB_ENV
    - run: echo '::set-output name=FOO_OUTPUT::$foo'
      id: foo_step
    - uses: actions/checkout@v2
    - uses: ./.github/actions/output
      with:
        text: 'some custom text'
    - run: echo "${{ steps.foo_step.outputs.FOO_OUTPUT }}"
