on: workflow_dispatch
jobs:
  npm-install-github:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node: [14, 16]
    steps:
      - name: Checkout nextstrain.org
        uses: actions/checkout@v3.1.0
        with:
          repository: nextstrain/nextstrain.org
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - run: npm ci
      - run: npm install nextstrain/auspice#d3d184519e0307dfbf1be398d8025255bc4918a3
      - run: cat package.json | jq '.dependencies.auspice'
  npm-install-clone:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node: [14, 16]
    env:
      AUSPICE_REPO_DIR: auspice
      NEXTSTRAIN_ORG_REPO_DIR: nextstrain.org
    steps:
      - name: Checkout nextstrain.org
        uses: actions/checkout@v3.1.0
        with:
          repository: nextstrain/nextstrain.org
          path: ${{ env.NEXTSTRAIN_ORG_REPO_DIR }}
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - run: npm ci
        working-directory: ${{ env.NEXTSTRAIN_ORG_REPO_DIR }}
      - name: Checkout auspice
        uses: actions/checkout@v3.1.0
        with:
          path: ${{ env.AUSPICE_REPO_DIR }}
          repository: nextstrain/auspice
          ref: d3d184519e0307dfbf1be398d8025255bc4918a3
      - run: cd ${{ env.AUSPICE_REPO_DIR }} && npm ci
      - run: npm install $GITHUB_WORKSPACE/$AUSPICE_REPO_DIR
        working-directory: ${{ env.NEXTSTRAIN_ORG_REPO_DIR }}
      - run: cat package.json | jq '.dependencies.auspice'
