on: push
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - run: echo "foo=${{ github.event_name == 'push' }}" >> $GITHUB_ENV
    - run: echo "FALSE_VALUE=${{ github.event_name != 'push' }}" >> $GITHUB_ENV
    - uses: actions/checkout@v2
    - uses: ./.github/actions/output
      with:
        text: 'some custom text'
    - uses: ./.github/actions/output
      with:
        text: ${{ env.FALSE_VALUE && 'this is a string' }}
